/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */
#include <stdio.h>
#include <stdlib.h>
#include <GL/glut.h>
#include <math.h>
#include <time.h>

#define MAX_BODIES 100
#define G 6.67428e-11
#define MIN_MASS 100
#define MAX_MASS 1000
#define MIN_R 2
#define MAX_R 10

typedef struct {
	float mass;
	float xpos;
	float ypos;
	float radius;
	float color_r;
	float color_g;
	float color_b;
} Body;

void add_body(int x, int y);
float ranf(float low, float high);

int num_bodies;
Body bodies[MAX_BODIES];

void draw_ball(int i) {
	glPushMatrix();
		glTranslatef(bodies[i].xpos,bodies[i].ypos,0);
		glColor3f(bodies[i].color_r, bodies[i].color_g, bodies[i].color_b);
		glBegin(GL_QUADS);
			glVertex2d(-bodies[i].radius,bodies[i].radius);
			glVertex2d(bodies[i].radius,bodies[i].radius);
			glVertex2d(bodies[i].radius,-bodies[i].radius);
			glVertex2d(-bodies[i].radius,-bodies[i].radius);
		glEnd();
	glPopMatrix();
}

void draw_state(void) {
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

	int i;
	for(i = 0; i < num_bodies; i++) {
		draw_ball(i);
	}
	glutSwapBuffers();
}

void sim_step(void) {
	
}

void special_press(int key, int x, int y) {
	printf("special key %d pressed\n",key);
}

void key_press(unsigned char key, int x, int y) {
	if (key == 27) 
		exit(0);
	else if (key == 'c') {
		printf("Count: %d\n",num_bodies);
	}
}

void mouse_click(int button, int state, int x, int y) {
	if(state == GLUT_UP) {
		//printf("mouse clicked at %d, %d\n",x,y);
		add_body(x,y);
	}
}

void add_body(int x, int y) {
	if(num_bodies == MAX_BODIES) {
		printf("max number of bodies reached!\n");
	}
	else {
		bodies[num_bodies].mass = ranf(MIN_MASS,MAX_MASS);
		bodies[num_bodies].radius = ranf(MIN_R,MAX_R);
		bodies[num_bodies].color_r = ranf(0,1);
		bodies[num_bodies].color_g = ranf(0,1);
		bodies[num_bodies].color_b = ranf(0,1);
		bodies[num_bodies].xpos = x;
		bodies[num_bodies].ypos = y;
		num_bodies++;
	}
}

float ranf(float low, float high) {
	float temp = (rand() / ((float)RAND_MAX + 1.0)) * (high - low) + low;
	return temp;
}

int main(int argc, char **argv)
{
	srand(time(NULL));

	glutInit(&argc, argv);
	glutInitDisplayMode(GLUT_DEPTH | GLUT_DOUBLE | GLUT_RGBA);
	glutInitWindowPosition(100,100);
	glutInitWindowSize(500,500);
	glutCreateWindow("Gravity Simulation");

	glutSpecialFunc(special_press);
	glutKeyboardFunc(key_press);
	glutIdleFunc(sim_step);
	//glutReshapeFunc(change_size);
	glutMouseFunc(mouse_click);
	glutDisplayFunc(draw_state);

	glutMainLoop();
	return (0);
}
